**SCIKIT API Reference**

In [1]:
# sklearn config
import sklearn._config as skl
skl.get_config()

{'assume_finite': False,
 'working_memory': 1024,
 'print_changed_only': True,
 'display': 'diagram',
 'pairwise_dist_chunk_size': 256,
 'enable_cython_pairwise_dist': True,
 'array_api_dispatch': False,
 'transform_output': 'default',
 'enable_metadata_routing': False,
 'skip_parameter_validation': False}

In [2]:
# Estimators
import numpy as np
from sklearn.base import BaseEstimator
# Definición de Estimador custom que utiliza un valor fijo para realizar predicciones
class MyEstimator(BaseEstimator):
  def __init__(self, *, mean):
    self.mean = mean
  def fit(self, X, y=None):
    self.is_fitted_ = True
    return self
  def predict(self, X):
    # Retorna una matriz unidimensional con tantos valores como muestras del conjunto
    # de datos y cada valor corresponde al parámetro 'mean'
    return np.full(shape=X.shape[0], fill_value=self.mean)
# Ejemplo de uso
estimator = MyEstimator(mean=5)
print(estimator.get_params())
X = np.array([
  [1, 2],
  [2, 3],
  [3, 4],
])
y = np.array([
  1,
  0,
  1
])
# Ajusto al modelo sin parametrizar (mean por defecto es 5)
result = estimator.fit(X, y).predict(X)
# La predicción es 5
print(result)
X_feature1 = X[0:,0:1]
X_feature2 = X[0:,1:2]
print("Valores de la feature1:\n", X_feature1)
print("Valores de la feature2:\n", X_feature2)
X_feature1_mean = np.mean(X_feature1)
X_feature2_mean = np.mean(X_feature2)
# Establezco parámetro mean a la media de la feature1 y vuelvo a ajustar
result = estimator.set_params(mean=X_feature1_mean).fit(X, y).predict(X)
# La predicción es 2 (media de la feature1)
print(result)

{'mean': 5}
[5 5 5]
Valores de la feature1:
 [[1]
 [2]
 [3]]
Valores de la feature2:
 [[2]
 [3]
 [4]]
[2. 2. 2.]


In [3]:
# Otros métodos interesantes de los estimadores
print(f"Metadata: {estimator.get_metadata_routing()}")
print(f"Parameters: {estimator.get_params()}")

Metadata: {}
Parameters: {'mean': np.float64(2.0)}


In [4]:
# Classifiers
from sklearn.base import ClassifierMixin
class MyClassifier(ClassifierMixin, BaseEstimator):
  def __init__(self, *, mean=5):
    self.mean = mean
  def fit(self, X, y=None):
    self.is_fitted = True
    return self
  def predict(self, X):
    return np.full(shape=X.shape[0], fill_value=self.mean)
classifier = MyClassifier(mean=1)
predict1 = classifier.fit(X, y).predict(X)
print(f"Predición realizada por clasificador: {predict1}")
score = classifier.score(X, y)
print(f"Precisión de la predicción: {score:.2f} %")
# Medición del error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y, predict1)
print(f"Media de errores absolutos: {mae:.2f}")

Predición realizada por clasificador: [1 1 1]
Precisión de la predicción: 0.67 %
Media de errores absolutos: 0.33


In [5]:
# Transformers
from sklearn.base import TransformerMixin
class MyTransform(TransformerMixin, BaseEstimator):
  def __init__(self, *, filled=0):
    self.filled = filled
  def fit(self, X, y=None):
    return self
  def transform(self, X):
    return X / 100
transform = MyTransform()
print("X antes de transformar\n", X)
X_ = transform.fit_transform(X)
print("X tras de transformar\n", X_)

X antes de transformar
 [[1 2]
 [2 3]
 [3 4]]
X tras de transformar
 [[0.01 0.02]
 [0.02 0.03]
 [0.03 0.04]]
